Add missing GDK_KEY_VoidSymbol #define.
Else the build with fail with `pqiv.c:4446:20: error: 'GDK_KEY_VoidSymbol' undeclared (first use in this function)`